"""add product marketing fields

Revision ID: 0002_product_marketing
Revises: 0001_initial_schema
Create Date: 2026-09-29 17:07:33.240399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002_product_marketing'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('graphic', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('products', 'graphic', server_default=None)
    op.add_column('products', sa.Column('classification', sa.String(length=40), nullable=True))
    op.add_column('products', sa.Column('worlds', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('gallery', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'gallery')
    op.drop_column('products', 'worlds')
    op.drop_column('products', 'classification')
    op.drop_column('products', 'graphic')
    # ### end Alembic commands ###
