import React from 'react';
import { ArrowUpRight, Heart, Plus, Minus, ShoppingBag } from 'lucide-react';
import { Product, asset, money } from './catalog';
import { useStore, go } from './store';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
export function Choice({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:{value:string;label:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="choice" aria-label={label}><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>;}
export function Action({children,to,secondary=false,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{to?:string;secondary?:boolean}){return <button {...props} className={`action ${secondary?'secondary':''} ${props.className||''}`} onClick={to?()=>go(to):props.onClick}>{children}</button>;}
export function IconButton({label,children,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{label:string}){return <button {...props} className={`icon-btn ${props.className||''}`} aria-label={label} title={label}>{children}</button>;}
export function PageHeading({eyebrow,title,count}:{eyebrow:string;title:string;count?:number}){return <div className="page-heading"><span className="eyebrow">{eyebrow}</span><h1>{title}{count!==undefined&&<sup>{count.toString().padStart(2,'0')}</sup>}</h1></div>;}
export function SectionHeading({small,title,to}:{small:string;title:string;to?:string}){return <div className="section-heading"><div><span className="eyebrow">{small}</span><h2>{title}</h2></div>{to&&<a className="text-link" href={'#'+to}>View all <ArrowUpRight size={18}/></a>}</div>;}
export function ProductCard({product:p,onQuick}:{product:Product;onQuick:(p:Product)=>void}){const {data,toggleWish}=useStore();return <article className="product-card"><div className="product-photo"><a href={'#/product/'+p.id}><img src={asset(p.image)} alt={p.name} loading="lazy"/></a><span className="product-badge">{p.isNew?'NEW DROP':p.fit==='Oversized'?'OVERSIZED':'ESSENTIAL'}</span><IconButton className="wish-btn" label={data.wishlist.includes(p.id)?'Remove '+p.name+' from wishlist':'Save '+p.name} aria-pressed={data.wishlist.includes(p.id)} onClick={()=>toggleWish(p.id)}><Heart size={19} fill={data.wishlist.includes(p.id)?'currentColor':'none'}/></IconButton><button className="quick-add" onClick={()=>onQuick(p)}>Choose size <Plus size={16}/></button></div><a href={'#/product/'+p.id}><h3>{p.name}</h3></a><p className="product-meta">{p.fit} fit · {p.sleeve}</p><div className="price-row"><strong>{money(p.price)}</strong><del>{money(p.mrp)}</del><span className="swatch" style={{background:p.color.toLowerCase()}} title={p.color}/></div></article>;}
export function Quantity({value,onChange,label='Quantity'}:{value:number;onChange:(n:number)=>void;label?:string}){return <div className="quantity"><IconButton label={'Decrease '+label} disabled={value<=1} onClick={()=>onChange(value-1)}><Minus size={14}/></IconButton><span aria-live="polite">{value}</span><IconButton label={'Increase '+label} disabled={value>=10} onClick={()=>onChange(value+1)}><Plus size={14}/></IconButton></div>;}
export function EmptyState({title,text}:{title:string;text:string}){return <div className="empty-state"><ShoppingBag size={45} strokeWidth={1}/><h2>{title}</h2><p>{text}</p><Action to="/shop">Explore the tees <ArrowUpRight size={18}/></Action></div>;}
